function createBus2()
busCell = { ...
        { ...
            'params', ...
            'MyHeader.h', ...
            'Some description', ...
            'Exported', ...
            '-1', ...
            {...
            {'M',1,'double', -1,'real','Sample'}, ...
            {'m',1,'double', -1,'real','Sample'}, ...
            {'g',1,'double', -1,'real','Sample'}, ...
            {'l',1,'double', -1,'real','Sample'}, ...
            {'b',1,'double', -1,'real','Sample'}, ...
            {'B',1,'double', -1,'real','Sample'}, ...
            }...
        }, ...
        };
Simulink.Bus.cellToObject(busCell)
end

